6-module
js-tasks-ru/jsbasic-20230302_guliev pull request #13
Opened 2023-04-06 05:56 UTC by GulievAnar31

2023-04-06 05:57 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-04-06 13:00 UTC, SinimaWath requested changes

2023-04-06 13:00 UTC, SinimaWath commented on 6-module/1-task/index.js
> +     table.appendChild(tBody);
Давай создание DOM елемента переделаем на шаблон:
```
const table = document.createElement('table');
table.innerHTML = `
<thead>
<tr>
  <th>Имя</th>
  <th>Возраст</th>
  <th>Зарплата</th>
  <th>Город</th>
  <th></th>
</tr>
</thead>
<tbody>
   ${this.rows.map((row) => `
      <tr>
         ....
      </tr>
   `).join('')}
</tbody>

`
```

2023-04-06 13:00 UTC, SinimaWath commented on 6-module/2-task/index.js
> +    button.alt = 'icon';
Создание карточки давай переделаем на шаблон:
```

this.elem = createElement(this.#template());
```

Как в примере на лекции https://codepen.io/sinimawath/pen/zYJQpqK?editors=0011

2023-04-07 06:10 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-04-08 13:04 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-04-09 13:52 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-04-09 19:52 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-04-10 16:57 UTC, SinimaWath approved these changes

2023-04-10 16:58 UTC, merged