7-module
js-tasks-ru/jsbasic-20230302_guliev pull request #14
Opened 2023-04-15 11:11 UTC by GulievAnar31

2023-04-15 11:12 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-04-15 11:32 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2023-04-20 06:45 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2023-04-21 09:25 UTC, SinimaWath requested changes

2023-04-21 09:25 UTC, SinimaWath commented on 8-module/2-task/index.js
> +      let productCard = new ProductCard(product);
У тебя нет класса `card`, у карточек товара, поэтому он их не может найти. Добавь в корневой елемент в ProductCard class `.card` либо здесь

2023-04-21 09:25 UTC, SinimaWath commented on 8-module/4-task/index.js
> +    this.modal.selectModal('body').appendChild(this.cartMarkup);
У тебя у класса Modal, нет  метода `selectModal`

2024-07-11 08:05 UTC, closed without merging